version: '3.4'

services:
  vote_session_db:
    image: mysql:8.0
    restart: always
    volumes:
      - vote_session_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vote_session_manager
    ports:
      - 3306:3306

volumes:
  vote_session_db:
    driver: "local"
