server.port: 8089
spring:
  application:
    name: vote-session-manager

  datasource:
    url: jdbc:mysql://localhost:3306/vote_session_manager
    username: root
    password: root
    continue-on-error: true
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
      format_sql: true
    show-sql: true

spring-doc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /
    disable-swagger-default-url: true