server.port: 8089
spring:
  application:
    name: vote-session-manager
  flyway:
    url: jdbc:mysql://localhost:3306/vote_session_manager?createDatabaseIfNotExist=true
    user: root
    password: root
    schemas:
      - vote_session_manager
  datasource:
    url: jdbc:mysql://localhost:3306/vote_session_manager
    username: root
    password: root
    continue-on-error: true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false

spring-doc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /
    disable-swagger-default-url: true

associate:
  url: http://localhost:8080/v1/associates
user-info:
  url: https://user-info.herokuapp.com/users

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic



